BASE: ["cifar10-sdt-base.yaml"]

MODEL:
  NAME: sdt-base
  NUM_CLASSES: 10
  PATCH_SIZE: 16
  NUM_HEADS: 8
  EMBED_DIMS: 256
  MLP_RATIO: 4.0
  NUM_LAYERS: 4
  POOL_STAT: "_1111"
  SPIKE_T: 4


OPTIMIZER:
  OPT: sgd

LR_SCHEDULER:
  LR: 5e-4
  MIN_LR: 3e-5
  CYCLE_EPOCHS: 140
  CYCLE_LIMIT: 1
  CYCLE_DECAY: 0.5
  CYCLE_MULT: 1.0
  WARMUP_EPOCHS: 60
  WARMUP_LR: 1e-6
  WARMUP_PREFIX: true

  