BASE: ["cifar10-base.yaml"]

DATA:
  IMG_SIZE: 224

MODEL:
  NAME: ResNet50

OPTIMIZER:
  OPT: sgd

LR_SCHEDULER:
  LR: 1e-3
  MIN_LR: 6e-5
  CYCLE_EPOCHS: 140
  CYCLE_LIMIT: 2
  CYCLE_DECAY: 0.5
  CYCLE_MULT: 1.0
  WARMUP_EPOCHS: 60
  WARMUP_LR: 1e-6
  WARMUP_PREFIX: true