wandb_version: 1

BASE:
  desc: null
  value:
  - ''
LOG_LEVEL:
  desc: null
  value: 20
TAG:
  desc: null
  value: default
SAVE_FREQ:
  desc: null
  value: 1
PRINT_FREQ:
  desc: null
  value: 10
OUTPUT:
  desc: null
  value: output\sdt-base\default
SEED:
  desc: null
  value: 0
EVAL_MODE:
  desc: null
  value: false
EVAL_METRIC:
  desc: null
  value: top1
DATA:
  desc: null
  value:
    IMG_SIZE: 224
    CHANNELS: 3
    BATCH_SIZE: 4
    VAL_BATCH_SIZE: 32
    DATA_PATH: /data1/hzh/imagenet
    DATASET: imagenet
MODEL:
  desc: null
  value:
    NAME: sdt-base
    NUM_CLASSES: 1000
    PATCH_SIZE: 16
    NUM_HEADS: 8
    EMBED_DIMS: 512
    MLP_RATIO: 1.0
    NUM_LAYERS: 4
    POOL_STAT: '1111'
    SPIKE_MODE: lif
    SPIKE_T: 4
    BACKEND: torch
    RESUME: false
    RESUME_PATH: ''
    INIT_CHECKPOINT: false
    CHECKPOINT_PATH: ''
    PRETRAINED: false
    PRETRAINED_PATH: ''
TRAIN:
  desc: null
  value:
    TET: false
    START_EPOCH: 0
    EPOCHS: 200
    BCE_LOSS: false
    JSD_LOSS: false
    LABEL_SMOOTH: 0.1
OPTIMIZER:
  desc: null
  value:
    OPT: sgd
    EPS: null
    BETAS: null
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0001
    CLIP_GRAD: null
    CLIP_MODE: norm
LR_SCHEDULER:
  desc: null
  value:
    SCHED: step
    LR: 0.01
    WARMUP_LR: 0.0001
    DECAY_EPOCHS: 30
    WARMUP_EPOCHS: 3
    DECAY_RATE: 0.1
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708659388.919923
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 63
      - 71
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.16.3
      6: 4.36.2
      8:
      - 3
      - 5
      13: windows-amd64
