SAVE_FREQ: 50
SEED: 42
DIST_EVAL: True

DATA:
  DATASET: cifar10
  IMG_SIZE: 32
  CHANNELS: 3
  BATCH_SIZE: 256
  VAL_BATCH_SIZE: 256
  DATA_PATH: ""

MODEL:
  NAME: sdt-base
  NUM_CLASSES: 10
  PATCH_SIZE: 4
  NUM_HEADS: 8
  EMBED_DIMS: 256
  MLP_RATIO: 4.0
  NUM_LAYERS: 2
  POOL_STAT: "0011"
  SPIKE_T: 4

TRAIN:
  ACCUM_ITER: 1
  TET: false
  START_EPOCH: 0
  EPOCHS: 200
  LABEL_SMOOTH: 0.0

OPTIMIZER:
  OPT: adamw
  WEIGHT_DECAY: 6e-2

LR_SCHEDULER:
  SCHED: cosine
  LR: 3e-4
  MIN_LR: 1e-5
  COOLDOWN_EPOCHS: 10
  WARMUP_EPOCHS: 20
  WARMUP_LR: 1e-6
